/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWatchlistRouteImport } from './routes/app.watchlist'
import { Route as AppStreamsRouteImport } from './routes/app.streams'
import { Route as AppSignalsRouteImport } from './routes/app.signals'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRealmsRouteImport } from './routes/app.realms'
import { Route as AppProfessionsRouteImport } from './routes/app.professions'
import { Route as AppPricingRouteImport } from './routes/app.pricing'
import { Route as AppPartnersRouteImport } from './routes/app.partners'
import { Route as AppNewsRouteImport } from './routes/app.news'
import { Route as AppLootRouteImport } from './routes/app.loot'
import { Route as AppForecastRouteImport } from './routes/app.forecast'
import { Route as AppDiscordRouteImport } from './routes/app.discord'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamsRoute = AppStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRealmsRoute = AppRealmsRouteImport.update({
  id: '/realms',
  path: '/realms',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessionsRoute = AppProfessionsRouteImport.update({
  id: '/professions',
  path: '/professions',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppLootRoute = AppLootRouteImport.update({
  id: '/loot',
  path: '/loot',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscordRoute = AppDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/compare': typeof AppCompareRoute
  '/app/discord': typeof AppDiscordRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/loot': typeof AppLootRoute
  '/app/news': typeof AppNewsRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/professions': typeof AppProfessionsRoute
  '/app/realms': typeof AppRealmsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/app/streams': typeof AppStreamsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/compare': typeof AppCompareRoute
  '/app/discord': typeof AppDiscordRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/loot': typeof AppLootRoute
  '/app/news': typeof AppNewsRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/professions': typeof AppProfessionsRoute
  '/app/realms': typeof AppRealmsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/app/streams': typeof AppStreamsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/compare': typeof AppCompareRoute
  '/app/discord': typeof AppDiscordRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/loot': typeof AppLootRoute
  '/app/news': typeof AppNewsRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/professions': typeof AppProfessionsRoute
  '/app/realms': typeof AppRealmsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/app/streams': typeof AppStreamsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/compare'
    | '/app/discord'
    | '/app/forecast'
    | '/app/loot'
    | '/app/news'
    | '/app/partners'
    | '/app/pricing'
    | '/app/professions'
    | '/app/realms'
    | '/app/settings'
    | '/app/signals'
    | '/app/streams'
    | '/app/watchlist'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/compare'
    | '/app/discord'
    | '/app/forecast'
    | '/app/loot'
    | '/app/news'
    | '/app/partners'
    | '/app/pricing'
    | '/app/professions'
    | '/app/realms'
    | '/app/settings'
    | '/app/signals'
    | '/app/streams'
    | '/app/watchlist'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/compare'
    | '/app/discord'
    | '/app/forecast'
    | '/app/loot'
    | '/app/news'
    | '/app/partners'
    | '/app/pricing'
    | '/app/professions'
    | '/app/realms'
    | '/app/settings'
    | '/app/signals'
    | '/app/streams'
    | '/app/watchlist'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/streams': {
      id: '/app/streams'
      path: '/streams'
      fullPath: '/app/streams'
      preLoaderRoute: typeof AppStreamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/signals': {
      id: '/app/signals'
      path: '/signals'
      fullPath: '/app/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/realms': {
      id: '/app/realms'
      path: '/realms'
      fullPath: '/app/realms'
      preLoaderRoute: typeof AppRealmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professions': {
      id: '/app/professions'
      path: '/professions'
      fullPath: '/app/professions'
      preLoaderRoute: typeof AppProfessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/partners': {
      id: '/app/partners'
      path: '/partners'
      fullPath: '/app/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loot': {
      id: '/app/loot'
      path: '/loot'
      fullPath: '/app/loot'
      preLoaderRoute: typeof AppLootRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forecast': {
      id: '/app/forecast'
      path: '/forecast'
      fullPath: '/app/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discord': {
      id: '/app/discord'
      path: '/discord'
      fullPath: '/app/discord'
      preLoaderRoute: typeof AppDiscordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDiscordRoute: typeof AppDiscordRoute
  AppForecastRoute: typeof AppForecastRoute
  AppLootRoute: typeof AppLootRoute
  AppNewsRoute: typeof AppNewsRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppPricingRoute: typeof AppPricingRoute
  AppProfessionsRoute: typeof AppProfessionsRoute
  AppRealmsRoute: typeof AppRealmsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppStreamsRoute: typeof AppStreamsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCompareRoute: AppCompareRoute,
  AppDiscordRoute: AppDiscordRoute,
  AppForecastRoute: AppForecastRoute,
  AppLootRoute: AppLootRoute,
  AppNewsRoute: AppNewsRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppPricingRoute: AppPricingRoute,
  AppProfessionsRoute: AppProfessionsRoute,
  AppRealmsRoute: AppRealmsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppStreamsRoute: AppStreamsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
